### ISSUE TITLE
Use Case: Transaction Rollback

### ISSUE THREAD

**Issue by mikependon** [Grauenwolf/DotNet-ORM-Cookbook#36] opened 2020-01-03 05:25 UTC
An ORM should show how to to transaction in a rolled-back state.

This should be validated after the operation.

- [ ] Test cases
- [ ] ADO
- [ ] Chain
- [ ] Dapper
- [ ] EF Core
- [ ] NHibernate
- [ ] RepoDB
- [ ] ServiceStack
- [ ] Documentation  
- [ ] LLBL Gen Pro

**Comment by Grauenwolf** [comment] 2020-01-03 05:30
I'm inclined to put the Commit and Rollback into the same use case. But we can talk about it more later.

**Comment by Grauenwolf** [comment] 2020-01-18 01:05
Duplicate of #35

**Closed by Grauenwolf** 2020-01-18 01:05 UTC
Labels: Use Case Proposal, duplicate
